{% set name = "opentelemetry-instrumentation-celery" %}
{% set version = "0.46b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_celery-{{ version }}.tar.gz
  sha256: 688b157c1fdddc48b4fdd029d35b4f3472cc2100b38914e3203b9bef9f15cd7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.46b0
    - opentelemetry-semantic-conventions ==0.46b0
    # - pytest 
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-celery 
    # - importlib-metadata ==4.13.0
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-celery
  summary: OpenTelemetry Celery Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
