{% set name = "opentelemetry-instrumentation-celery" %}
{% set version = "0.60b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_celery-{{ version }}.tar.gz
  sha256: e19e23141c0c8529b2aa75f7d6ec50252828fc7d18329d711bf4df2ca94213bb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.60b0
    - opentelemetry-semantic-conventions ==0.60b0
    # - pytest 
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-celery 
    # - importlib-metadata ==4.13.0
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-celery 
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0
    # - celery <6.0,>=4.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-celery
  summary: OpenTelemetry Celery Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
